# Generated by Django 4.2.16 on 2025-06-20 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ForeignKey(blank=True, limit_choices_to={'media_type': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail_for_product', to='assets.media', verbose_name='Thumbnail'),
        ),
    ]
