# Generated by Django 4.2.16 on 2025-06-29 01:40

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_categoryinteraction_categoryanalytics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='categoryinteraction',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Category Interactions'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_selections', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='topic',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='sub_category', chained_model_field='parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_selections', to='products.category'),
        ),
    ]
