# Generated by Django 4.2.16 on 2025-06-30 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_categoryinteraction_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('share', 'Share'), ('wishlist', 'Wishlist'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('purchase', 'Purchase'), ('custom_event', 'Custom Event')], max_length=20),
        ),
        migrations.AlterField(
            model_name='color',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product'),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='products.product'),
        ),
        migrations.AlterField(
            model_name='material',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='products.product'),
        ),
        migrations.AlterField(
            model_name='size',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='products.product'),
        ),
    ]
