# Generated by Django 4.2.16 on 2025-07-15 04:26

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0002_shippingaddress_apartment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('cart', '0002_cart_coupon_alter_cart_shipping_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Sin descuentos ni envío', max_digits=10)),
                ('items_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento total por ítems', max_digits=10)),
                ('global_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento global del cupón', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total final a pagar', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagada'), ('fulfilled', 'Enviada/Entregada'), ('canceled', 'Cancelada')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='ID de la pasarela de pago', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.coupon')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.shippingaddress')),
                ('shipping_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.shippingmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('item_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='(unit_price * quantity) - item_discount', max_digits=10)),
                ('size_title', models.CharField(blank=True, max_length=100)),
                ('weight_title', models.CharField(blank=True, max_length=100)),
                ('material_title', models.CharField(blank=True, max_length=100)),
                ('color_title', models.CharField(blank=True, max_length=100)),
                ('flavor_title', models.CharField(blank=True, max_length=100)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['order', 'item_name'],
                'indexes': [models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'), models.Index(fields=['content_type', 'object_id'], name='orders_orde_content_9c040d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
    ]
