# Generated by Django 4.2.16 on 2025-07-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Número de seguimiento proporcionado por el transportista', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='URL para rastrear el envío en el sitio del transportista', null=True),
        ),
    ]
