services:
    # Django
    django_ecommerce:
        container_name: django_ecommerce
        build: .
        command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - ecommerce_redis
            - ecommerce_db
    
    # Redis
    ecommerce_redis:
        image: redis
        container_name: ecommerce_redis
        ports:
            - 6379:6380
    
    # Database
    ecommerce_db:
        image: postgres
        container_name: ecommerce_db
        restart: always
        environment:
            POSTGRES_DB: django_db
            POSTGRES_USER: django
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        volumes:
            - .dbdata:/var/lib/postgresql