# Generated by Django 4.2.16 on 2025-07-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='apartment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
