# Generated by Django 4.2.16 on 2025-07-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('last_names', models.CharField(max_length=255)),
                ('identification', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('complaint', models.TextField()),
                ('selected_application', models.CharField(choices=[('complaint', 'Complaint'), ('grievance', 'Grievance')], max_length=10)),
                ('selected_method', models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('affiliate', 'Affiliate'), ('anonymous', 'Anonymous')], max_length=10)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
