# Generated by Django 4.2.16 on 2025-07-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_useraccount_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
