# Generated by Django 4.2.16 on 2025-06-29 18:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.UUIDField(blank=True, null=True)),
                ('size', models.UUIDField(blank=True, null=True)),
                ('weight', models.UUIDField(blank=True, null=True)),
                ('material', models.UUIDField(blank=True, null=True)),
                ('color', models.UUIDField(blank=True, null=True)),
                ('flavor', models.UUIDField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.wishlist')),
            ],
        ),
    ]
